### ISSUE TITLE
Plugin doesn't load on PaperMC 1.20.6

### ISSUE THREAD

**Issue by APiggyInABukkit** [Ste3et/FurnitureMaker#8]
Hello! I've been trying to use this plugin on PaperMC 1.20.6 but the plugin doesn't load and gives this error:

```
[Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'FurnitureMaker-2.3.0 (1).jar' in folder 'plugins\.paper-remapped'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:129) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:532) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	... 9 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at FurnitureMaker-2.3.0 (1).jar/de.Ste3et_C0st.DiceFunitureMaker.FurnitureMakerPlugin.getBukkitVersion(FurnitureMakerPlugin.java:108) ~[FurnitureMaker-2.3.0 (1).jar:?]
	at FurnitureMaker-2.3.0 (1).jar/de.Ste3et_C0st.DiceFunitureMaker.FurnitureMakerPlugin.getVersionInt(FurnitureMakerPlugin.java:96) ~[FurnitureMaker-2.3.0 (1).jar:?]
	at FurnitureMaker-2.3.0 (1).jar/de.Ste3et_C0st.DiceFunitureMaker.FurnitureMakerPlugin.<clinit>(FurnitureMakerPlugin.java:33) ~[FurnitureMaker-2.3.0 (1).jar:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.for
Name(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	... 9 more
```

I'm running PaperMC 1.20.6 #147, FurnitureLib-3.2.1, FurnitureMaker-2.3.0 and the latest ProtocolLib dev build (as of writing, #723)
And here is the full server start up log: [latest.log](https://github.com/user-attachments/files/16043719/latest.log)

**Comment by Ste3et** [comment]
I will correct it asap as i find a timeslot of my Day to fix it please pay Attention in Spigot.

Regrads Ste3et_C0st

**Comment by Ste3et** [comment]
https://www.spigotmc.org/resources/furnituremaker.20667/updates

Sorry that update should fix your problem.

**Comment by APiggyInABukkit** [comment]
I updated the plugin and it loaded with no issues, thanks! 😁
